# Generated by Django 4.1.7 on 2023-12-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
